import { Permission, SystemRole } from '@aegis/shared-enums';

export const ALL_PERMISSIONS = Object.values(Permission);

/** Sensible default role -> permission catalog for the seeded system roles. */
export const ROLE_PERMS: Record<SystemRole, Permission[]> = {
  [SystemRole.Owner]: ALL_PERMISSIONS,
  [SystemRole.Admin]: ALL_PERMISSIONS,
  [SystemRole.Manager]: [
    Permission.UserView,
    Permission.RoleView,
    Permission.TeamManage,
    Permission.OrgManage,
    Permission.TagCreate,
    Permission.TagUpdate,
    Permission.TagDelete,
    Permission.TagList,
    Permission.RecordTagAdd,
    Permission.RecordTagRemove,
    Permission.RecordAssign,
    Permission.TeamTagManage,
    Permission.ExpenseReportView,
    Permission.ExpenseReportApprove,
    Permission.ExpenseReportReject,
    Permission.InvoiceView,
    Permission.InvoiceApprove,
    Permission.ReportRun,
    Permission.ReportView,
    Permission.AuditView,
  ],
  [SystemRole.Approver]: [
    Permission.ExpenseReportView,
    Permission.ExpenseReportApprove,
    Permission.ExpenseReportReject,
    Permission.InvoiceView,
    Permission.InvoiceApprove,
    Permission.TagList,
  ],
  [SystemRole.Contributor]: [
    Permission.ExpenseReportCreate,
    Permission.ExpenseReportView,
    Permission.ExpenseReportUpdate,
    Permission.ExpenseReportSubmit,
    Permission.InvoiceCreate,
    Permission.InvoiceView,
    Permission.InvoiceUpdate,
    Permission.TagList,
  ],
  [SystemRole.Viewer]: [
    Permission.ExpenseReportView,
    Permission.InvoiceView,
    Permission.ReportView,
    Permission.UserView,
    Permission.RoleView,
    Permission.TagList,
  ],
  [SystemRole.PayrollAdmin]: [
    Permission.PayrollEmployeeView,
    Permission.PayrollEmployeeManage,
    Permission.PayrollSensitiveRead,
    Permission.PayRunCreate,
    Permission.PayRunCalculate,
    Permission.PayslipViewAll,
    Permission.ConnectorManage,
    Permission.ConnectorPush,
    Permission.TagList,
  ],
  [SystemRole.PayrollApprover]: [
    Permission.PayrollEmployeeView,
    Permission.PayRunApprove,
    Permission.PayslipViewAll,
    Permission.TagList,
  ],
  [SystemRole.FinanceDisburser]: [
    Permission.PayRunDisburse,
    Permission.PayslipViewAll,
    Permission.ExpenseReportView,
    Permission.ExpenseReportReimburse,
    Permission.TagList,
  ],
  [SystemRole.Auditor]: [
    Permission.AuditView,
    Permission.UserView,
    Permission.RoleView,
    Permission.PermissionView,
    Permission.PolicyView,
    Permission.SessionView,
    Permission.ExpenseReportView,
    Permission.InvoiceView,
    Permission.ReportView,
    Permission.TagList,
  ],
  [SystemRole.Employee]: [
    Permission.ExpenseReportCreate,
    Permission.ExpenseReportView,
    Permission.ExpenseReportSubmit,
    Permission.PayslipViewOwn,
    Permission.TagList,
  ],
};
